### ISSUE TITLE
Short abbreviation for mongoDb Id

### ISSUE THREAD

**Issue by kfk12688** [Sharavanth/ho-app#47]
In Tableview the reference fieldType only show their reference id.

**Comment by Sharavanth** [comment]
Shorter ID's would look better and take lesser screen space

![image](https://user-images.githubusercontent.com/9451020/33236937-f5165eb4-d289-11e7-9e30-2459b0371c97.png)


Since, the mongoDb id cannot be shortened without losing data (see [this](https://stackoverflow.com/questions/14306931/shorten-mongodb-id-in-javascript)), the only way forward would be to truncate the text

**Comment by kfk12688** [comment]
Truncation results in repetition. see screenshot

![image](https://user-images.githubusercontent.com/23191491/33252008-49a0af70-d361-11e7-816c-1513ebd250dd.png)
